-- +goose Up
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS full_name VARCHAR(255);
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS desired_position VARCHAR(255);
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS about TEXT;
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS city VARCHAR(255);

-- +goose Down
ALTER TABLE resumes DROP COLUMN IF EXISTS user_id;
ALTER TABLE resumes DROP COLUMN IF EXISTS full_name;
ALTER TABLE resumes DROP COLUMN IF EXISTS desired_position;
ALTER TABLE resumes DROP COLUMN IF EXISTS about;
ALTER TABLE resumes DROP COLUMN IF EXISTS city;