-- +goose Up
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS telegram VARCHAR(100);
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS github VARCHAR(255);
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS linkedin VARCHAR(255);

-- +goose Down
ALTER TABLE resumes DROP COLUMN IF EXISTS phone;
ALTER TABLE resumes DROP COLUMN IF EXISTS telegram;
ALTER TABLE resumes DROP COLUMN IF EXISTS github;
ALTER TABLE resumes DROP COLUMN IF EXISTS linkedin;