-- +goose Up
ALTER TABLE users ADD COLUMN IF NOT EXISTS photo_url VARCHAR(255);
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS photo_url VARCHAR(255);
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS views INTEGER DEFAULT 0;

-- +goose Down
ALTER TABLE users DROP COLUMN IF EXISTS photo_url;
ALTER TABLE resumes DROP COLUMN IF EXISTS photo_url;
ALTER TABLE resumes DROP COLUMN IF EXISTS views;